---
new_page_extension: md
auto_deploy: false
admin_path: "/src/admin"
webhook_url: 
sections:
- type: directory
  path: content/notes
  label: Notes
  create: documents
  match: "**/*"
  new_doc_ext: mdx
  templates:
  - note
- type: directory
  path: content/essays
  label: Essays
  create: all
  match: "**/*"
  new_doc_ext: mdx
  templates:
  - essay
- type: directory
  path: content/works
  label: Works
  create: all
  match: "**/*"
  new_doc_ext: mdx
upload_dir: src/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - GATSBY_ALGOLIA_APP_ID=7YF1M80D7K
  - GATSBY_ALGOLIA_SEARCH_KEY=102fd20f90c8caa279c5a7570bfb9e8d
  - ALGOLIA_ADMIN_KEY=72eb974e35601e921d5db29afc98f722
  preview_output_directory: public
  install_dependencies_command: yarn
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
